const seedTracks = [
  {
    "id": "ccmixter-70544",
    "title": "Geppetto V4 Subversive",
    "artist": "coruscate",
    "description": "Faixa Creative Commons selecionada para leitura no Tomoverso. Tags: media, remix, editorial_pick, bpm_075_080, alternate, attribution, audio, mp3, 44k, stereo",
    "mood": "rain",
    "genre": "lofi / leitura",
    "duration_seconds": 214,
    "file_url": "/audio/tomomusic/tracks/01-geppetto-v4-subversive-coruscate.mp3",
    "cover_url": "/audio/tomomusic/covers/01-geppetto-v4-subversive-coruscate.svg",
    "source_url": "https://ccmixter.org/files/Coruscate/70544",
    "license_name": "Attribution (4.0)",
    "license_url": "https://creativecommons.org/licenses/by/4.0/",
    "attribution_required": true,
    "attribution_text": "Geppetto V4 Subversive — coruscate (Attribution (4.0)). Fonte: https://ccmixter.org/files/Coruscate/70544. Licença: https://creativecommons.org/licenses/by/4.0/",
    "source": "ccMixter",
    "downloaded_at": "2026-07-09T14:57:05.236Z",
    "local_file": "public/audio/tomomusic/tracks/01-geppetto-v4-subversive-coruscate.mp3",
    "bytes": 3423548
  },
  {
    "id": "ccmixter-65250",
    "title": "Distant Fantasy",
    "artist": "Doxent Zsigmond",
    "description": "Faixa Creative Commons selecionada para leitura no Tomoverso. Tags: sample, media, ccplus, multiple_formats, attribution, audio, mp3, 44k, stereo, VBR",
    "mood": "fantasy",
    "genre": "jazz lofi",
    "duration_seconds": 151,
    "file_url": "/audio/tomomusic/tracks/02-distant-fantasy-doxent-zsigmond.mp3",
    "cover_url": "/audio/tomomusic/covers/02-distant-fantasy-doxent-zsigmond.svg",
    "source_url": "https://ccmixter.org/files/doxent/65250",
    "license_name": "Attribution (3.0)",
    "license_url": "http://creativecommons.org/licenses/by/3.0/",
    "attribution_required": true,
    "attribution_text": "Distant Fantasy — Doxent Zsigmond (Attribution (3.0)). Fonte: https://ccmixter.org/files/doxent/65250. Licença: http://creativecommons.org/licenses/by/3.0/",
    "source": "ccMixter",
    "downloaded_at": "2026-07-09T14:57:26.988Z",
    "local_file": "public/audio/tomomusic/tracks/02-distant-fantasy-doxent-zsigmond.mp3",
    "bytes": 2491189
  },
  {
    "id": "ccmixter-70048",
    "title": "Get Some Sleep",
    "artist": "coruscate",
    "description": "Faixa Creative Commons selecionada para leitura no Tomoverso. Tags: media, remix, bpm_110_115, rough_mix, attribution, audio, mp3, 44k, stereo, CBR",
    "mood": "sleep",
    "genre": "lofi / leitura",
    "duration_seconds": 205,
    "file_url": "/audio/tomomusic/tracks/03-get-some-sleep-coruscate.mp3",
    "cover_url": "/audio/tomomusic/covers/03-get-some-sleep-coruscate.svg",
    "source_url": "https://ccmixter.org/files/Coruscate/70048",
    "license_name": "Attribution (4.0)",
    "license_url": "https://creativecommons.org/licenses/by/4.0/",
    "attribution_required": true,
    "attribution_text": "Get Some Sleep — coruscate (Attribution (4.0)). Fonte: https://ccmixter.org/files/Coruscate/70048. Licença: https://creativecommons.org/licenses/by/4.0/",
    "source": "ccMixter",
    "downloaded_at": "2026-07-09T14:57:37.145Z",
    "local_file": "public/audio/tomomusic/tracks/03-get-some-sleep-coruscate.mp3",
    "bytes": 3276844
  },
  {
    "id": "ccmixter-70890",
    "title": "brume de hâte (AI Échantillons)",
    "artist": "LostieTS",
    "description": "Faixa Creative Commons selecionada para leitura no Tomoverso. Tags: media, remix, bpm_180_185, multiple_formats, attribution, audio, mp3, 44k, stereo, VBR",
    "mood": "chill",
    "genre": "lofi / leitura",
    "duration_seconds": 224,
    "file_url": "/audio/tomomusic/tracks/04-brume-de-hate-ai-echantillons-lostiets.mp3",
    "cover_url": "/audio/tomomusic/covers/04-brume-de-hate-ai-echantillons-lostiets.svg",
    "source_url": "https://ccmixter.org/files/LostieTS/70890",
    "license_name": "Attribution (4.0)",
    "license_url": "https://creativecommons.org/licenses/by/4.0/",
    "attribution_required": true,
    "attribution_text": "brume de hâte (AI Échantillons) — LostieTS (Attribution (4.0)). Fonte: https://ccmixter.org/files/LostieTS/70890. Licença: https://creativecommons.org/licenses/by/4.0/",
    "source": "ccMixter",
    "downloaded_at": "2026-07-09T14:58:32.162Z",
    "local_file": "public/audio/tomomusic/tracks/04-brume-de-hate-ai-echantillons-lostiets.mp3",
    "bytes": 3589058
  },
  {
    "id": "ccmixter-69064",
    "title": "November's Rain",
    "artist": "Skye Jordan",
    "description": "Faixa Creative Commons selecionada para leitura no Tomoverso. Tags: sample, media, bpm_075_080, attribution, audio, mp3, 44k, stereo, CBR, mid",
    "mood": "lofi",
    "genre": "lofi / leitura",
    "duration_seconds": 158,
    "file_url": "/audio/tomomusic/tracks/05-november-s-rain-skye-jordan.mp3",
    "cover_url": "/audio/tomomusic/covers/05-november-s-rain-skye-jordan.svg",
    "source_url": "https://ccmixter.org/files/SkyeJordan/69064",
    "license_name": "Attribution (4.0)",
    "license_url": "https://creativecommons.org/licenses/by/4.0/",
    "attribution_required": true,
    "attribution_text": "November's Rain — Skye Jordan (Attribution (4.0)). Fonte: https://ccmixter.org/files/SkyeJordan/69064. Licença: https://creativecommons.org/licenses/by/4.0/",
    "source": "ccMixter",
    "downloaded_at": "2026-07-09T14:59:06.563Z",
    "local_file": "public/audio/tomomusic/tracks/05-november-s-rain-skye-jordan.mp3",
    "bytes": 3797203
  },
  {
    "id": "ccmixter-56739",
    "title": "Lost Beyond",
    "artist": "PorchCat",
    "description": "Faixa Creative Commons selecionada para leitura no Tomoverso. Tags: halloween, ghost_notes, sample, stems, media, attribution, audio, mp3, 44k, stereo",
    "mood": "fantasy",
    "genre": "lofi / leitura",
    "duration_seconds": 159,
    "file_url": "/audio/tomomusic/tracks/06-lost-beyond-porchcat.mp3",
    "cover_url": "/audio/tomomusic/covers/06-lost-beyond-porchcat.svg",
    "source_url": "https://ccmixter.org/files/PorchCat/56739",
    "license_name": "Attribution (3.0)",
    "license_url": "http://creativecommons.org/licenses/by/3.0/",
    "attribution_required": true,
    "attribution_text": "Lost Beyond — PorchCat (Attribution (3.0)). Fonte: https://ccmixter.org/files/PorchCat/56739. Licença: http://creativecommons.org/licenses/by/3.0/",
    "source": "ccMixter",
    "downloaded_at": "2026-07-09T14:59:15.529Z",
    "local_file": "public/audio/tomomusic/tracks/06-lost-beyond-porchcat.mp3",
    "bytes": 3818519
  },
  {
    "id": "ccmixter-68991",
    "title": "Nature Travellers",
    "artist": "Skye Jordan",
    "description": "Faixa Creative Commons selecionada para leitura no Tomoverso. Tags: media, secret_mixter, remix, celebratory_20, bpm_120_125, attribution, audio, mp3, 44k, stereo",
    "mood": "lofi",
    "genre": "lofi / leitura",
    "duration_seconds": 166,
    "file_url": "/audio/tomomusic/tracks/07-nature-travellers-skye-jordan.mp3",
    "cover_url": "/audio/tomomusic/covers/07-nature-travellers-skye-jordan.svg",
    "source_url": "https://ccmixter.org/files/SkyeJordan/68991",
    "license_name": "Attribution (3.0)",
    "license_url": "http://creativecommons.org/licenses/by/3.0/",
    "attribution_required": true,
    "attribution_text": "Nature Travellers — Skye Jordan (Attribution (3.0)). Fonte: https://ccmixter.org/files/SkyeJordan/68991. Licença: http://creativecommons.org/licenses/by/3.0/",
    "source": "ccMixter",
    "downloaded_at": "2026-07-09T14:59:39.260Z",
    "local_file": "public/audio/tomomusic/tracks/07-nature-travellers-skye-jordan.mp3",
    "bytes": 3989046
  },
  {
    "id": "ccmixter-69196",
    "title": "South Side Jingle Bells",
    "artist": "Skye Jordan",
    "description": "Faixa Creative Commons selecionada para leitura no Tomoverso. Tags: season_stars, sample, stem, media, bpm_090_095, attribution, audio, mp3, 44k, stereo",
    "mood": "lofi",
    "genre": "lofi / leitura",
    "duration_seconds": 101,
    "file_url": "/audio/tomomusic/tracks/08-south-side-jingle-bells-skye-jordan.mp3",
    "cover_url": "/audio/tomomusic/covers/08-south-side-jingle-bells-skye-jordan.svg",
    "source_url": "https://ccmixter.org/files/SkyeJordan/69196",
    "license_name": "Attribution (4.0)",
    "license_url": "https://creativecommons.org/licenses/by/4.0/",
    "attribution_required": true,
    "attribution_text": "South Side Jingle Bells — Skye Jordan (Attribution (4.0)). Fonte: https://ccmixter.org/files/SkyeJordan/69196. Licença: https://creativecommons.org/licenses/by/4.0/",
    "source": "ccMixter",
    "downloaded_at": "2026-07-09T14:59:50.289Z",
    "local_file": "public/audio/tomomusic/tracks/08-south-side-jingle-bells-skye-jordan.mp3",
    "bytes": 4059473
  },
  {
    "id": "ccmixter-70365",
    "title": "Frostbreak",
    "artist": "coruscate",
    "description": "Faixa Creative Commons selecionada para leitura no Tomoverso. Tags: sample, media, ccplus, bpm_090_095, rough_mix, attribution, audio, mp3, 44k, stereo",
    "mood": "ambient",
    "genre": "ambient",
    "duration_seconds": 266,
    "file_url": "/audio/tomomusic/tracks/09-frostbreak-coruscate.mp3",
    "cover_url": "/audio/tomomusic/covers/09-frostbreak-coruscate.svg",
    "source_url": "https://ccmixter.org/files/Coruscate/70365",
    "license_name": "Attribution (4.0)",
    "license_url": "https://creativecommons.org/licenses/by/4.0/",
    "attribution_required": true,
    "attribution_text": "Frostbreak — coruscate (Attribution (4.0)). Fonte: https://ccmixter.org/files/Coruscate/70365. Licença: https://creativecommons.org/licenses/by/4.0/",
    "source": "ccMixter",
    "downloaded_at": "2026-07-09T15:00:34.913Z",
    "local_file": "public/audio/tomomusic/tracks/09-frostbreak-coruscate.mp3",
    "bytes": 4263646
  },
  {
    "id": "ccmixter-68985",
    "title": "pushoutfromyourshore",
    "artist": "martinsea",
    "description": "Faixa Creative Commons selecionada para leitura no Tomoverso. Tags: media, secret_mixter, remix, celebratory_20, bpm_070_075, ccplus, attribution, audio, mp3, 44k",
    "mood": "reading",
    "genre": "lofi / leitura",
    "duration_seconds": 208,
    "file_url": "/audio/tomomusic/tracks/10-pushoutfromyourshore-martinsea.mp3",
    "cover_url": "/audio/tomomusic/covers/10-pushoutfromyourshore-martinsea.svg",
    "source_url": "https://ccmixter.org/files/softmartin/68985",
    "license_name": "Attribution (3.0)",
    "license_url": "http://creativecommons.org/licenses/by/3.0/",
    "attribution_required": true,
    "attribution_text": "pushoutfromyourshore — martinsea (Attribution (3.0)). Fonte: https://ccmixter.org/files/softmartin/68985. Licença: http://creativecommons.org/licenses/by/3.0/",
    "source": "ccMixter",
    "downloaded_at": "2026-07-09T15:01:33.018Z",
    "local_file": "public/audio/tomomusic/tracks/10-pushoutfromyourshore-martinsea.mp3",
    "bytes": 4938495
  }
] as const;

export default seedTracks;
