import type { SiteSettings } from "./types";

export const DEFAULT_SITE_SETTINGS: Omit<SiteSettings, "created_at" | "updated_at"> = {
  id: "default",
  site_name: "Tomo Verso Editora",
  site_tagline: "onde histórias ganham vida.",
  hero_badge: "Editora digital de histórias",
  hero_title: "Tomo Verso Editora",
  hero_highlight: "onde histórias ganham vida.",
  hero_description: "A Tomo Verso Editora é uma editora digital dedicada a transformar histórias em experiências marcantes. Nosso objetivo é conectar leitores e autores através de obras envolventes, criativas e acessíveis, reunindo novels, light novels, mangás, manhwas, livros e narrativas originais em um só universo.",
  primary_cta_label: "Ler mangás",
  primary_cta_href: "/manga",
  secondary_cta_label: "Explorar novels",
  secondary_cta_href: "/explore",
  publish_cta_label: "Publicar",
  publish_cta_href: "/auth/signup",
  footer_tagline: "A Tomo Verso Editora nasceu para aproximar leitores de histórias que realmente combinam com eles — seja fantasia, romance, ação, drama, comédia, isekai, aventura ou qualquer universo capaz de despertar curiosidade. Mais do que uma editora, somos um ponto de encontro para quem vive histórias.",
  support_email: "tomoversoeditora@gmail.com",
  github_url: null,
  discord_url: null,
  telegram_url: null,
  maintenance_mode: 0,
  maintenance_message: "Estamos fazendo ajustes no painel e na loja. Algumas áreas podem mudar ao longo do dia.",
  storefront_enabled: 1,
  storefront_title: "Loja Tomo Verso Editora",
  storefront_description: "Prepare o catálogo para vender livros, mangás, bundles e edições digitais a partir do mesmo painel.",
  storefront_href: "/store",
};

export const ADMIN_NAV_ITEMS = [
  { href: "/admin", label: "Visão geral", section: "overview" },
  { href: "/admin/site", label: "Site principal", section: "site" },
  { href: "/admin/catalog", label: "Catálogo", section: "catalog" },
  { href: "/admin/users", label: "Usuários", section: "users" },
  { href: "/admin/sellers", label: "Autores vendedores", section: "sellers" },
  { href: "/admin/commerce", label: "Commerce", section: "commerce" },
  { href: "/admin/integrations", label: "Integrações", section: "integrations" },
  { href: "/admin/imports", label: "Importações", section: "imports" },
  { href: "/admin/stats", label: "Estatísticas", section: "stats" },
  { href: "/admin/security", label: "Segurança", section: "security" },
] as const;
